# Generated by Django 2.1.3 on 2018-11-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mowimu_inventory', '0002_auto_20181117_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='inside_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contains_place', to='mowimu_inventory.Place'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contains_thing', to='mowimu_inventory.Place'),
        ),
    ]
